# coding: utf8
import tingbot
from tingbot import *
import random
import requests
import time

current_saying = 'Loading'

api_location = 'Braithwaite, UK'

def render_expression(expression):
    
    output = ''
    e_iter = iter(expression)
    
    try:
        while True:
            c = e_iter.next()
    
            if c == '[':
                group = ''
    
                c = e_iter.next()
    
                while c != ']':
                    group += c
                    c = e_iter.next()
    
                choices = group.split('|')
    
                output += random.choice(choices)
            else:
                output += c
    except StopIteration:
        pass
    
    return output

@tingbot.every(seconds=60)
def current_weather():
    print 'refreshing...'
    
    r = requests.get('https://query.yahooapis.com/v1/public/yql', params={
        'q': 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="%s") and u="c"' % api_location,
        'format': 'json',
    })
    
    r.raise_for_status()
    
    api_data = r.json()
    
    channel = api_data['query']['results']['channel']
    item = channel['item']
    condition = item['condition']
    
    code = int(condition['code'])

    weather_words = weather_words_map[code]
    
    global current_saying
    
    current_saying = render_expression(weather_words)
    
def loop():
    # drawing code here
    screen.fill(
        color=(255,255,255))
        
    screen.text(
        current_saying,
        align='center',
        max_width=(280),
        color='black',
        font='ArnoPro-Caption.otf',
        font_size=30)
        
    screen.text(
        '-\n@GrisedalePike',
        align='center',
        color='black',
        xy=(160, 220),
        font='Futura LT Medium.ttf',
        font_size=12)

weather_words_map = {
    0: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  tornado
    1: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  tropical storm
    2: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  hurricane
    3: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  severe thunderstorms
    4: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  thunderstorms
    5: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \'at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mixed rain and snow
    6: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \'at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mixed rain and sleet
    7: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \'at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mixed snow and sleet
    8: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s fair mizzlin|some spots o\' rain yance or twice|it\'ll rain nin, but it may hadder a bit|it mizzles a bit but it won\'t be mich rain|It nobbut spits|a spot o\' mizzle|ther\'s sum scotch mist o\' roond aboot] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  freezing drizzle
    9: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s fair mizzlin|some spots o\' rain yance or twice|it\'ll rain nin, but it may hadder a bit|it mizzles a bit but it won\'t be mich rain|It nobbut spits|a spot o\' mizzle|ther\'s sum scotch mist o\' roond aboot] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  drizzle
    10: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s gae wet|bit drizzly|weshed oowt|rain iv\'ry whoar|it\'s syling|it\'s hossin\' it doown|it\'s gae hossin\' it doown|it\'s hoyin it doown|it\'s yukken it doown|varra showery, thee might even\'t catch sight\'t weather-go|rain t\'looks reglar|\'tis set to rain o\' roond|Ah\'s sowenly wrong if it\'s nut gaan ta rain|Ars wet t\'skin an\' hasn\'\'t a dhry threed aboot ma|it\'s raining pitchforks with the tines downwards|it hadders and roaks|thee\'ll git clarted up iffen thee gaan\'s oowt in\'t this|Ah\'d nut heng aboowt if ah wuh thee, ther\'s rain on\'t way] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  freezing rain
    11: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s gae wet|bit drizzly|weshed oowt|rain iv\'ry whoar|it\'s syling|it\'s hossin\' it doown|it\'s gae hossin\' it doown|it\'s hoyin it doown|it\'s yukken it doown|varra showery, thee might even\'t catch sight\'t weather-go|rain t\'looks reglar|\'tis set to rain o\' roond|Ah\'s sowenly wrong if it\'s nut gaan ta rain|Ars wet t\'skin an\' hasn\'\'t a dhry threed aboot ma|it\'s raining pitchforks with the tines downwards|it hadders and roaks|thee\'ll git clarted up iffen thee gaan\'s oowt in\'t this|Ah\'d nut heng aboowt if ah wuh thee, ther\'s rain on\'t way] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  showers
    12: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s gae wet|bit drizzly|weshed oowt|rain iv\'ry whoar|it\'s syling|it\'s hossin\' it doown|it\'s gae hossin\' it doown|it\'s hoyin it doown|it\'s yukken it doown|varra showery, thee might even\'t catch sight\'t weather-go|rain t\'looks reglar|\'tis set to rain o\' roond|Ah\'s sowenly wrong if it\'s nut gaan ta rain|Ars wet t\'skin an\' hasn\'\'t a dhry threed aboot ma|it\'s raining pitchforks with the tines downwards|it hadders and roaks|thee\'ll git clarted up iffen thee gaan\'s oowt in\'t this|Ah\'d nut heng aboowt if ah wuh thee, ther\'s rain on\'t way] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  showers
    13: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  snow flurries
    14: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  light snow showers
    15: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  blowing snow
    16: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  snow
    17: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  hail
    18: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  sleet
    19: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Ars a bit clammy|it\'s lookin\' like a hazy yan|gae dusty] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  dust
    20: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s hunch-weather|them poor Herwicks in\'t this fog] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  foggy
    21: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Ars a bit clammy|it\'s lookin\' like a hazy yan|gae dusty] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  haze
    22: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Ars a bit clammy|it\'s lookin\' like a hazy yan|gae dusty] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  smoky
    23: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Ars fair jiggered, it\'s gae windy | Tek hod o\'yersel, it\'s gae windy|T\'helm wind\'d vanya bleht gyeas nebs off|t’ wind booasums a gae deal|T\' wind com bealen doon of Cross Fell heets a helm rough and loud|that\'s a flowe find reet eniuf|there\'s a fuff o\' wind\'d put leet oot|T\'wind\'s fuffen aboowt first oot o’yah art an than oot ov anudder|When t\'wind blows hard frae Stowgill eyast, ye may foad yer sheep an\' hoose yer beyast|it\'s blaowin a gial|there\'s a snarlin wind|O\'s gahn ta be snirped up i\' t\' posters if this dufty wind gahs on mich langer|Noo, it\'s a snizen mack ov a day|it\'s gae blowy, strang eniuf tae bleht gyeas nebs aff|A tell you \'tis a day wud blaw t\'horns off the kye] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  blustery
    24: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Ars fair jiggered, it\'s gae windy | Tek hod o\'yersel, it\'s gae windy|T\'helm wind\'d vanya bleht gyeas nebs off|t’ wind booasums a gae deal|T\' wind com bealen doon of Cross Fell heets a helm rough and loud|that\'s a flowe find reet eniuf|there\'s a fuff o\' wind\'d put leet oot|T\'wind\'s fuffen aboowt first oot o’yah art an than oot ov anudder|When t\'wind blows hard frae Stowgill eyast, ye may foad yer sheep an\' hoose yer beyast|it\'s blaowin a gial|there\'s a snarlin wind|O\'s gahn ta be snirped up i\' t\' posters if this dufty wind gahs on mich langer|Noo, it\'s a snizen mack ov a day|it\'s gae blowy, strang eniuf tae bleht gyeas nebs aff|A tell you \'tis a day wud blaw t\'horns off the kye] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  windy
    25: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Its gae cawd tedae. Put thi kitle on, ort even\'t gert cooat|Ars reet nithered|It\'s starvin\'|Ars frozzen|here\'s a sharp mwornin\' lad!|Ther\'s a bone in the air|it\'s a sly day|it\'s peel-a-bone weather] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  cold
    26: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  cloudy
    27: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mostly cloudy (night)
    28: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mostly cloudy (day)
    29: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  partly cloudy (night)
    30: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  partly cloudy (day)
    31: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] Ars bin gaely thrang tedae wi\'t sun oowt|Lookin\' varra glisky|it fare to be a wunnerful glossy morning|Hesta ivver sin a grander dae] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  clear (night)
    32: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] Ars bin gaely thrang tedae wi\'t sun oowt|Lookin\' varra glisky|it fare to be a wunnerful glossy morning|Hesta ivver sin a grander dae] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  sunny
    33: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Aahs in fine fettle, the hesta cum visit|Tis reet grand|it\'ll be reet|lookin\' fair \t’middlin\'|it\'s varra lown|it\'s a grand day|nae rain in sight|Hesta ivver sin a grander dae|lookin\' grand|it\'s nobbut fine] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  fair (night)
    34: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Aahs in fine fettle, the hesta cum visit|Tis reet grand|it\'ll be reet|lookin\' fair \t’middlin\'|it\'s varra lown|it\'s a grand day|nae rain in sight|Hesta ivver sin a grander dae|lookin\' grand|it\'s nobbut fine] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  fair (day)
    35: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s gae wet|bit drizzly|weshed oowt|rain iv\'ry whoar|it\'s syling|it\'s hossin\' it doown|it\'s gae hossin\' it doown|it\'s hoyin it doown|it\'s yukken it doown|varra showery, thee might even\'t catch sight\'t weather-go|rain t\'looks reglar|\'tis set to rain o\' roond|Ah\'s sowenly wrong if it\'s nut gaan ta rain|Ars wet t\'skin an\' hasn\'\'t a dhry threed aboot ma|it\'s raining pitchforks with the tines downwards|it hadders and roaks|thee\'ll git clarted up iffen thee gaan\'s oowt in\'t this|Ah\'d nut heng aboowt if ah wuh thee, ther\'s rain on\'t way] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  mixed rain and hail
    36: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s mighty wharm|It\'s gae whaarm|Ars Black brussin\'|T\'s hay meken weather|it\'s as dry as kesh, ther\'s noowt mich ta be gitten oot ov a kesh|it\'s pipin\' hot|that\'s eniuf o\' that heat] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  hot
    37: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  isolated thunderstorms
    38: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  scattered thunderstorms
    39: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  scattered thunderstorms
    40: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s gae wet|bit drizzly|weshed oowt|rain iv\'ry whoar|it\'s syling|it\'s hossin\' it doown|it\'s gae hossin\' it doown|it\'s hoyin it doown|it\'s yukken it doown|varra showery, thee might even\'t catch sight\'t weather-go|rain t\'looks reglar|\'tis set to rain o\' roond|Ah\'s sowenly wrong if it\'s nut gaan ta rain|Ars wet t\'skin an\' hasn\'\'t a dhry threed aboot ma|it\'s raining pitchforks with the tines downwards|it hadders and roaks|thee\'ll git clarted up iffen thee gaan\'s oowt in\'t this|Ah\'d nut heng aboowt if ah wuh thee, ther\'s rain on\'t way] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  scattered showers
    41: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  heavy snow
    42: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  scattered snow showers
    43: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  heavy snow
    44: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [it\'s nut bad|a la\'l bit glum but fine and fair|lookin\' bright and nut sin oowt o\' t\'rain yit|lookin\' fair t\'middlin\'] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  partly cloudy
    45: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  thundershowers
    46: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [Am owerblawn wi\'t snow|snow iv\'ry whoar|we\'re gaan ta hev some doon-fo|take heed o\' that drufted-snow|ther\'s bin a grimin o\' snow|when it\'s snow \‘at\'s knee deep, it\'s deep eniuf!|t\'air\'s as full o\' snow as an egg\'s full o\' meat, an\' t\' winds driven an\' whirlen \'t aboot e\' o\' directions at yance|Stoor an\' drife fit ta blind yan|ther\'s a heavy rime on|snow\'s a fallin\', parlish soft|Thoo hesta put thi boots on if thu\'s gaan oot f\'t wark|T\' frost\'s played howder wi\'t me toes|Ah\'d nut heng aboowt if ah wuh thee, ther\'s snow on\'t way|Ah\'s sowenly wrong if it\'s nut gaan ta snow] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  snow showers
    47: '[Ennyrwoad|Hoow do|By gum|bloomin\' heck|\'kin \'el|Ho-way|To all me marra\'s oowt theyer|Well noow|Fair t\'say|Areet|Noow then|Hai\' (sharp intake of breath)|Eeeh|Oust fettal?] [On\'y\'t radgies\'d venture up here in\'t stormy wedder like this|Ars feelin\' fair wankle wit storm|oh it\'s blashy|it\'s varra clashy|T\'weather mends an\' pares|it\'s varra trashy|it\'s ower-kessen|t\'s gaan t\' thunner an\' rain|On\'y\'t claggers an\'d sheep on\'t fell|if skidder hath a cap, scruffle wots full well o\' that!] [on\'t top|up here|oowt theyer|tedae|like|reet noow|the noow|eh|abeun|in\'t it]', #  isolated thundershowers
}

# run the app
tingbot.run(loop)


